### ISSUE TITLE
I can not run this Project

### ISSUE THREAD

**Issue by CivelXu** [ethers-io/EthersWallet-ios#18]
I can not run this Project 😭😭😭😭😭😭

**Comment by ricmoo** [comment]
What error are you getting?

You must download this project as well as ethers.objc from our GitHub page, and have them both in the same directory.

Also, iOS 11 and iPhone X have layout issues which I will be submitting the fixes for soon.

**Comment by CivelXu** [comment]
Thank you for your help! I missed download ethers.objc. And Why not use Swift to implement it (ethers.objc). I need some implantation of Private key and Mnemonic from ethers.objc.

**Comment by ricmoo** [comment]
If you only need the Private Key and Mnemonic support, you can use Account directly from ethers.objc and may not need the EthersWallet-iOS package. This package is just the UI. The ethers.objc is a more general Ethereum library, which is pretty feature-similar to my ethers.js library.

Objective-C and Swift are both compatible with each other, and I've been doing iOS development since it launched, so I am much more familiar with Objective-C. I'm actually not really a fan of Swift...
