### ISSUE TITLE
Provide maximum spend amount, adjustable gas limits and warnings on insufficient funds.

### ISSUE THREAD

**Issue by emanuelelaface** [ethers-io/EthersWallet-ios#7]
When I create a new transaction on the iPhone application, I set the recipient, the number of ethers, the password and click on send, but the transaction doesn't appear in the list and nothing is done.
I am not sure how to give more details because there is no error neither any log.
The iOS is 10.2.1.

**Comment by ricmoo** [comment]
Is this the version released on the AppStore, or did you build it yourself? Both are be identical, just trying to get more details.

If you don't mind (no worries if you want to keep it private) could you send your address and the amount your are trying to send to support@ethers.io?

I will add error messages. My guess is that there is insufficient funds. The app currently uses a higher gas limit to allow for contracts, but I think it should offer a choice for the gas limit, (auto-detecting based on whether that destination address is a contract or externally owned account). So, even though the transaction cost will be much lower, the account must have enough funds to meet the limit.

That is my initial guess. I will start working on that feature this week.

I also have an online tool up later today/tomorrow that will allow you to use your wallet online, without the app if you need your funds sooner. Let me know and I can post it somewhere and give you early access.

**Comment by ricmoo** [comment]
There are a few UI improvements we need for sending:

- Allow the user to select gas limit (21000, medium contract, high contract; for example) and automatically detect which to use; for example, if the account has no code, it is an EAO and can safely use 21000 gas
- Provide a "max" option which will populate the amount field with largest spendable amount; for now, this will only support EOA addresses since the gas limit can be absolutely guaranteed.
- Warning when sending more than can be spent
- Warnings when a transaction will likely fail due to gas limit too low
- Error message to the user when a transaction fails

**Comment by ricmoo** [comment]
This is now added in v0.2 which has been published to the App Store.
