### ISSUE TITLE
Comma instead of dot?

### ISSUE THREAD

**Issue by emanuelelaface** [ethers-io/EthersWallet-ios#8]
In the iOS application, when try to send an ether, in the Amount field it appears a keypad with the numbers from 0 to 9, the delete and the comma to separate the decimal numbers.
The comma doesn't work, in the sense that when pressed nothing happen and you are able only to send integer number of ethers.
In reality you can send decimals if you copy-paste from another place, or if you insert the integer, then exit from the Amount field. It will set of you a .0 that you can further edit, but this is not handy.
I suspect that the comma is not accepted by the field because it is really sending a comma while the form expects a dot.

**Comment by ricmoo** [comment]
What locale are you using? Could you send a screen shot of your screen like the following to support@ethers.io?

Do you have a comma instead of a decimal there? I know locales like French Canadian use a comma instead of a decimal. I will update the App and test with French locales.

![img_0698](https://cloud.githubusercontent.com/assets/975687/23905436/7152ed16-08a1-11e7-9ba2-07ee7e81fcae.PNG)

**Comment by ricmoo** [comment]
Fixed in https://github.com/ethers-io/EthersWallet-ios/commit/f21e5b7c22121362de5ba2296cc92151ed9ab06e.

I will post a message here (and close the issue) once a version including this fix is posted to the App Store.

**Comment by ricmoo** [comment]
This is now fixed in v0.2 which has been published to the App Store.
